---
title: "Visualització de dades - PAC3"
author: "Daniel Vilaseca"
date: "6/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Primer carreguem les dades dels dos datasets:
data_world <- read.csv('C:/PRAC2/daily number of new reported COVID-19 cases and deaths worldwide.csv',stringsAsFactors = FALSE)
data_europe <- read.csv('C:/PRAC2/daily number of new reported COVID-19 cases and deaths by EU EEA country.csv', stringsAsFactors = FALSE)

# Analitzem les característiques globals dels datasets:
str(data_world)
```
```{r}
str(data_europe)
```

Fem els canvis de tipus de variable necessaris:
```{r}
# Canvis al conjunt de dades data_world:
data_world$dateRep <- as.Date(data_world$dateRep, "%d/%m/%Y")
data_world$day <- as.character(data_world$day)
data_world$month <- as.character(data_world$month)
data_world$year <- as.character(data_world$year)
str(data_world)
```
```{r}
# Canvis al conjunt de dades data_europe:
data_europe$dateRep <- as.Date(data_europe$dateRep, "%d/%m/%Y")
data_europe$day <- as.character(data_europe$day)
data_europe$month <- as.character(data_europe$month)
data_europe$year <- as.character(data_europe$year)
str(data_europe)
```

Haurem de combinar els dos conjunts de dades en un de sol:
```{r}
library(dplyr)
data_pac <- bind_rows(data_world, data_europe)
str(data_pac)
```

Finalment ens queda un conjunt de dades de 13 variables i 63.880 registres, que convertirem a csv:
```{r}
write.csv(data_pac, "C:/PRAC2/dades-diaries-covid.csv", row.names = FALSE)
```
